### PR TITLE
add login.py and edited auth.py

### PR DESCRIPTION
**Pull request by puyangogju**
added auth.py and login.py created login.py file and make a connection in auth.py

### CODE REVIEW

**Review by vol2468 — COMMENTED** [review]
Check login is not working. maybe you have to import from login.py?

**Comment by puyangogju** [comment]
> Code looks good except for importing. Couldn't test without database.

already put the import line in auth.py

**Comment by puyangogju** [comment]
> Check login is not working. maybe you have to import from login.py?

imported from login.py just now

**Review by vol2468 — APPROVED** [review]
Runs without any error

**Review by joyfuluj — APPROVED** [review]
It worked:)

**Pull request merged**
